# Generated by Django 5.0.7 on 2024-07-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.CharField(max_length=20),
        ),
    ]
